### PR TITLE
Dev 143

### PR DESCRIPTION
**Pull request by DeniceLayton**
Removed the grey border within the calculate sleep score section

### CODE REVIEW

**Review by onlyasmalllizard — CHANGES_REQUESTED** [review]
Thanks for removing the border!

There are still some CSS rules in styles.css that are related to putting the border in the right place. They'll all be applied to the #calculator id, and they'll be in media queries as well. Any width, height, top, and left settings should go. I'm pretty sure the "position: absolute" on line 215 can go too, but please test this to make sure it doesn't break anything!

**Comment by DeniceLayton** [comment]
Okay , try this , I have removed all redundant width height left and right settings for calculator and checked on mobile. I cannot remove the position:absolute; which you were referring to as it breaks it !.

**Comment by onlyasmalllizard** [comment]
Great, thank you!  I couldn't remember exactly which was put in just for the border and what was there for other reasons. :)

It looks like you have some conflicts that need to be resolved. Could you please merge the main branch into this and push again?

**Comment by DeniceLayton** [comment]
done, please check and confirm

**Comment by onlyasmalllizard** [comment]
Conflicts fixed and merged in!

**Pull request merged**
