### PR TITLE
set width to fit in with style

### PR DESCRIPTION
**Pull request by Jaytru1997**

### CODE REVIEW

**Review by onlyasmalllizard — CHANGES_REQUESTED** [review]
Hi Jay, thanks for working on this, and your solution does solve the problem. I think there's a simpler way to change the same thing that works with the grid system that's in place though.

If you look at line 816, grid-column is set to auto / span 2. Auto is there to work with the shorthand required for the grid-column rule, and if it was there by itself, without the span 2, you would see the text directly underneath the picture sharing the same width.

The span 2 is the part of this rule that has made this set of text so wide. It says that this element should stretch over two columns in the grid. If you change line 816 to "grid-column: 3;", you get the same effect as adding a width and changing the "justify-self" rule.

Could you please make the following changes?

1. Change the "grid-column" rule as detailed above.
2. Remove the width.
3. Change justify-self back to center.
4. Update the id name of this element to "col-3-row-3-item3" so that we don't get confused. This will need to be changed both in styles.css and in index.html

Thank you!

**Comment by Jaytru1997** [comment]
Alright! Will do

**Comment by Jaytru1997** [comment]
I've made the change to fit the laid out design. Thanks for reviewing!

**Comment by onlyasmalllizard** [comment]
Hi Jay, sorry to take a few days to get back to you on this. 

The code works well within the grid system now, but I really preferred your first choice on where to place the "Other Health Risks" text. I think having it in column 3, row 3 makes the whole section look more balanced. Could you please place the text there and make sure the class name reflects the updated location?

Thank you!

**Comment by Jaytru1997** [comment]
sure, will do!

Thanks for reviewing.

**Comment by Jaytru1997** [comment]
I made the changes to the code already. Kindly review and let me know.

**Review by onlyasmalllizard — CHANGES_REQUESTED** [review]
Hi Jay,

Everything is set on text width part we were discussing earlier, but your work on adding the border has ended up in the same PR. In the future, you can avoid this by working in different branches for each ticket you have active. You would then create your PR from your working branch instead of from your main branch. This article gives a basic explanation of how to use them: https://www.freecodecamp.org/news/how-to-use-branches-in-git/

For your border radius, could you please set all of your width and height rules in ems? These are responsive units and will adjust to different screen sizes better. There is a handy px to em converter here: https://www.w3schools.com/tags/ref_pxtoemconversion.asp

Once you have done this, could you please have a look at the sizing you've chosen for the image on mobile devices. At the moment, it is causing a horizontal scroll bar on small screens. I know Chrome has preset phone sizes in Developer Tools, and I'm sure other browsers do as well. Once you switch to a phone sized screen, reload the page to make sure it's not using style rules meant for larger screen sizes.

Thank you!

**Comment by Jaytru1997** [comment]
Alright, will do. Thanks for the measurement conversion info

**Comment by onlyasmalllizard** [comment]
Hi Jay, thanks for updating this. The horizontal scroll bar on mobile is still there, but having looked more closely, I'm not convinced it's caused by this section. I'm going to open a ticket to look into this as a bug.

You have some conflicts with the main branch. Could you please pull from upstream, resolve the conflicts, and push again? Then I can get this merged in.

**Comment by Jaytru1997** [comment]
I think the horizontal scroll bar is caused because the clouds aren't responsive. Check this out, perhaps it might be the issue.

**Comment by onlyasmalllizard** [comment]
Hi Jay, I've had an emergency come up. I've let cendei know the background of the work you've done, and she's going to comment shortly and support you for the rest of this ticket.

**Comment by Jaytru1997** [comment]
I'm sorry about that, I hope all is well with you. Be safe and good luck with whatever it is you're dealing with.

**Comment by DeniceLayton** [comment]
Hi Jay, 

I've caught up with this ticket, so in order to get this merged in we need to resolve the conflicts we have.  Have you had a chance  to look at the info I sent you on discord. about updating your local repository?

 One way we  can resolve the conflict is for you to  pull from upstream, you will then be able to resolve the conflict your end if GitHub needs you to,  and then  do another push. 
If you need any advice or assistance then please let me know id be happy to help.

 As for the issue with the scrollbars,  Lizard discovered that it might be an issue with the browser cache, as I couldn't see any scrollbar on mobile. If this occurs again we will open it on a separate ticket as a bug.

Let me know how you get on

Thanks

Denice

**Pull request merged**
